name: Publish Skeleton

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Build & Publish
    if: github.repository == 'skeletonlabs/skeleton'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: voidzero-dev/setup-vp@v1.21.0
        with:
          node-version: 24
          cache: true
      - run: npm install -g npm@latest
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v2.1.0
        with:
          pr-title: 'task: release'
          version-script: vp run changeset:version
          publish-script: vp run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
